### PR TITLE
Streamline the dev environment process

### PR DESCRIPTION
**Pull request by louh**
Trying some things, let me know how this feels @patriciogonzalezvivo @bcamper @nvkelso.

## Installation

Typing `npm install` also now builds all the required files (e.g. Modernizr). You no longer need to run `npm run build` after cloning.

## Running a local server

`gulp` now uses [Browsersync](https://www.browsersync.io). Amongst other things, it:

  - automatically runs a local server and opens Tangram Play in your system's default browser
  - reloads JavaScript and `index.html` when they change, in addition to live-reloading CSS.
  - please see the Browsersync documentatation for other features, which includes mirroring application state in other browsers and a UI panel (defaults to http://localhost:8081/). I've not fully explored all the options yet.

The previous default behavior of `gulp` is retained with the command `gulp watch`, which watches and rebuilds JavaScript and CSS, but does not run a local server or auto-reloads the application for you.

Additionally, the build process now displays JavaScript build errors as system notifications (and in console) instead of crashing Gulp completely.

## Other

I've updated `CONTRIBUTING.md` to reflect the above, and added an additional note about using Node's `http-server` module to run a local server with CORS enabled (for loading of local scene files).

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
👍  👍  👍  nice work!

**Comment by bcamper** [comment]
As a personal preference, I'm not so into have a terminal automatically launch my browser (I'm not sure it's a typical user expectation), but maybe that's just me. Maybe a command line option?

**Comment by louh** [comment]
I wasn't entirely sold on it myself, but it was default Browsersync
functionality, and I was mostly responding to an earlier offline comment
from @nvkelso to have one command "do everything" so I definitely wanted to
see how this felt. The option to turn off auto-browser-open is easy to add
but I'm somewhat inclined to leave it that way than to have another command
for it. Thoughts, Nathaniel?

**Comment by bcamper** [comment]
I'm actually finding this quite annoying :) In my typical flow, I leave
Play open all the time. If I ever have to restart gulp, it fires up a
second browser tab. You can run a second terminal command to do things like
git commands and leave gulp running, but this feels like an unnecessarily
"clever" feature to me...

**Comment by louh** [comment]
Oh boy, that's a good observation. Thankfully turning off the auto-open is an
easy option to set. I am updating it to *not* automatically open a browser.

On May 10 2016, at 4:45 pm, Brett Camper &lt;notifications@github.com&gt;
wrote:  

> I'm actually finding this quite annoying :) In my typical flow, I leave  
Play open all the time. If I ever have to restart gulp, it fires up a  
second browser tab. You can run a second terminal command to do things like  
git commands and leave gulp running, but this feels like an unnecessarily  
"clever" feature to me...  
  
On Tue, May 10, 2016 at 5:40 PM, Lou Huang &lt;notifications@github.com&gt;
wrote:  
  
&gt; I wasn't entirely sold on it myself, but it was default Browsersync  
&gt; functionality, and I was mostly responding to an earlier offline comment  
&gt; from @nvkelso to have one command "do everything" so I definitely wanted
to  
&gt; see how this felt. The option to turn off auto-browser-open is easy to
add  
&gt; but I'm somewhat inclined to leave it that way than to have another
command  
&gt; for it. Thoughts, Nathaniel?  
&gt;  
&gt; On Tue, May 10, 2016, 10:49 AM Brett Camper
&lt;notifications@github.com&gt;  
&gt; wrote:  
&gt;  
&gt; &gt; As a personal preference, I'm not so into have a terminal
automatically  
&gt; &gt; launch my browser (I'm not sure it's a typical user expectation),
but  
&gt; maybe  
&gt; &gt; that's just me. Maybe a command line option?  
&gt; &gt;  
&gt; &gt; —  
&gt; &gt; You are receiving this because you authored the thread.  
&gt; &gt; Reply to this email directly or view it on GitHub  
&gt; &gt; &lt;  
&gt; https://github.com/tangrams/tangram-
play/pull/348#issuecomment-218201789&gt;  
&gt;  
&gt; &gt;  
&gt;  
&gt; —  
&gt; You are receiving this because you were mentioned.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/tangrams/tangram-
play/pull/348#issuecomment-218300427&gt;  
&gt;  

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on
GitHub](https://github.com/tangrams/tangram-play/pull/348#issuecomment-2183015
83)

**Pull request merged**
