### PR TITLE
Cache example scene files

### PR DESCRIPTION
**Pull request by louh**
Following up from #434! This PR adds caching scene file YAMLs in the Tangram Play repository and unifies it with the earlier work for adding optimized thumbnails.

### CODE REVIEW

**Comment by bcamper** [comment]
There are some downsides to copying these to Play. I think it's especially important that the house styles stay recent, but I see you've excluded those, which is good. But, we've had a real issue with proliferation of scene files, particularly when new Tangram versions come out and we need to make updates. I could see it becoming very easy to forget to update one or the other of these (the Play vs. Sandbox copies), leading to various gotchas. (This came up this morning in a Tangram issue regarding a demo that hasn't been updated yet, so it's fresh in my mind.)

How much do we really gain by copying these vs. allowing them to be loaded from a canonical external location?

**Comment by louh** [comment]
I think the issue is that we _don't_ have a canonical location with the uptime support that I'd like. Our current "canonical external location" for Sandbox scene files is an unreliable Rawgit cache and when that is inaccessible then Tangram Play can have a broken experience. On the other hand, Mapzen house styles are hosted on mapzen.com, and so is Tangram Play, which means that usually if house styles go down then chances are Tangram Play is inaccessible too.

Furthermore we were already only linking to specific commit SHAs of the Sandbox scene files, rather than "always the latest one." This is because the _current_ scene files use imports which is not helpful until editor tabs are implemented. By locking Sandbox scenes to specific versions, we can guarantee that scene files "work as expected," and bump up its "version" when we need to (e.g. bug fix, Tangram update). If the problem is that someone might forget to update the scene file, it was already a problem before and not a new one introduced in this proposal.

**Comment by louh** [comment]
If we want to serve Sandbox scenes from `https://mapzen.com/carto/` I will definitely revoke this PR without further comment :)

**Comment by louh** [comment]
There are a grip of changes in this bundle that I wanted to merge, but the PR has been amended to _not_ cache scene files. The script to do so is still present in case it needs to be done.

**Pull request merged**
