### PR TITLE
Bump codemirror@5.12.0

### PR DESCRIPTION
**Pull request by louh**
Not built, but I'm vetting this version bump.

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
what this means?

**Comment by louh** [comment]
Steadily keeping up to date underlying dependencies

**Comment by patriciogonzalezvivo** [comment]
I see... should I do something?

**Comment by louh** [comment]
Merge?

**Comment by patriciogonzalezvivo** [comment]
Great!

**Pull request merged**
